---@diagnostic disable: missing-fields
return {}
-- return {
--   "nvim-treesitter/nvim-treesitter",
--   build = ":TSUpdate",
--   config = function()
--     local config = require("nvim-treesitter.configs")
--     config.setup({
--       auto_install = true,
--       ensure_installed = { "javascript", "lua", "json", "typescript", "html", "css", "markdown", "vue", "go" },
--       highlight = { enable = true },
--       indent = { enable = true },
--       playground = { enable = true },
--       autotag = { enable = true },
--       incremental_selection = {
--         enable = true,
--         keymaps = {
--           init_selection = "<C-space>",
--           node_incremental = "<C-space>",
--           scope_incremental = false,
--           node_decremental = "<bs>",
--         },
--       },
--     })
--   end,
-- }
